server.port=${PORT:8080}
spring.application.name=money-transfer-api
spring.threads.virtual.enabled=true

transfer.executor.workers=${TRANSFER_WORKERS:4}
transfer.executor.queue-capacity=${TRANSFER_QUEUE_CAPACITY:100}
